version: '3.8'

services:
    meditranslate:
        build: .
        ports:
         - "8501:8501"
        environment:
        - HF_TOKEN=${HF_TOKEN}
        volumes:
         - model_cache:/root/.cache
        restart: unless-stopped
    
volumes:
  model_cache:

